version: '3.8'

services:
    siu-site:
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - '9999:9999'
        environment:
            - NODE_ENV=production
        restart: unless-stopped
