name: Deploy to Production

on:
    push:
        branches: [main]
    workflow_dispatch:

jobs:
    deploy:
        runs-on: self-hosted
        if: github.ref == 'refs/heads/main'

        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Stop existing containers
              run: |
                  docker-compose down || true

            - name: Clean up old images
              run: |
                  docker image prune -f

            - name: Build Docker image
              run: |
                  docker-compose build --no-cache

            - name: Start containers
              run: |
                  docker-compose up -d

            - name: Verify environment variables
              run: |
                  echo "Checking if environment variables are loaded in container..."
                  docker-compose exec -T siu-web printenv | grep NEXT_PUBLIC_ || echo "No NEXT_PUBLIC_ variables found in container"
                  echo "Current redirect URI:"
                  docker-compose exec -T siu-web printenv NEXT_PUBLIC_GOOGLE_REDIRECT_URI || echo "NEXT_PUBLIC_GOOGLE_REDIRECT_URI not found"

            - name: Deployment success
              run: |
                  echo "Deployment completed successfully!"
